export const movieData = [
   
    {
        title:"Beast",
        description:"Beast is the latest Tamil action-movie featuring Atharvaa Murali, Tanya Ravichandran in the main roles.",
        image:"https://i0.wp.com/www.newsbugz.com/wp-content/uploads/2022/04/Beast-Mode.jpg?fit=1280%2C720&ssl=1"
    },
    {
        title:"KGF",
        description:"KGF is the latest Kanada action-movie featuring Atharvaa Murali, Tanya Ravichandran in the main roles.",
        image:"https://static.toiimg.com/thumb/msid-91740611,width-1280,height-720,resizemode-4/.jpg"
    },
    {
        title:"Parambara",
        description:"Parambara is the latest Tamil action-movie featuring Atharvaa Murali, Tanya Ravichandran in the main roles.",
        image:"images/img-2.jpg"
    },
    {
        title:"FIR",
        description:"FIR is the latest Tamil action-drama featuring Atharvaa Murali, Tanya Ravichandran in the main roles.",
        image:"images/img-4.webp"
    },
   
    {
        title:"Shoorveer",
        description:"Shoorveer is the latest Hindi action-movie featuring Atharvaa Murali, Tanya Ravichandran in the main roles.",
        image:"images/img-1.jpg"
    },
  
]

export const latest_movie = [
    {
        images:"images/last-1.jpg",
        category:"Latest",
    },
    {
        images:"https://lumiere-a.akamaihd.net/v1/images/p_blackwidow_21043_v2_6d1b73b8.jpeg",
        category:"Latest",
    },
    {
        images:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@like_202006280402.png,ox-24,oy-617,ow-29:q-80/et00302403-jmbsnyjdek-portrait.jpg",
        category:"Latest",
    },
    {
        images:"https://images.moviesanywhere.com/c9b039ffb143f8eea8b7d66d3cfd8949/8a030796-a13c-4acd-b88f-dbd2b161c0b1.jpg?h=375&resize=fit&w=250",
        category:"Latest",
    },
    {
        images:"https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@like_202006280402.png,ox-24,oy-617,ow-29:ote-MjlrIGxpa2Vz,ots-29,otc-FFFFFF,oy-612,ox-70:q-80/et00321392-umyvkwpqpa-portrait.jpg",
        category:"Latest",
    },
    {
        images:"https://akamaividz2.zee5.com/image/upload/w_504,h_756,c_scale,f_webp,q_auto:eco/resources/0-0-1z5156101/portrait/1920x770b428101cf0d84ef697a2b22e172a913b.jpg",
        category:"Latest",
    },
    {
        images:"https://www.filmibeat.com/img/320x100x392/popcorn/trending_news/watch:-the-grey-man-trailer-out-6076-20220525122747.jpg",
        category:"Latest",
    },
    {
        images:"https://lumiere-a.akamaihd.net/v1/images/p_aladdin2019_17638_d53b09e6.jpeg",
        category:"Latest",
    },
    {
        images:"https://dx35vtwkllhj9.cloudfront.net/trafalgarreleasing/blackpink/images/regions/gb/onesheet.jpg",
        category:"Latest",
    },
    {
        images:"https://www.filmibeat.com/img/320x100x392/popcorn/trending_news/brad-pitts-bullet-train-gets-a-release-date-6092-20220602121819.jpg",
        category:"Latest",
    },
    {
        images:"https://cdn.moviefone.com/admin-uploads/posters/super-pets-movie-poster_1656124357.jpg?d=360x540&q=50",
        category:"Latest",
    },
    {
        images:"https://www.commonsensemedia.org/sites/default/files/styles/ratio_2_3_medium/public/product-images/csm-movie/lightyear-movie-poster.jpeg",
        category:"Latest",
    },
    {
        images:"https://qqcdnpictest.mxplay.com/pic/dad5cca0b4edceb233748de3a4df7702/en/2x3/320x480/test_pic1655900073139.webp",
        category:"tamil",
    },
    {
        images:"https://moviegalleri.net/wp-content/gallery/tamil-deepavali-wishes-posters-2020/Kodiyil-Oruvan-Movie-Deepavali-Wishes-Posters.jpg",
        category:"tamil",
    },
    {
        images:"https://nettv4u.com/imagine/07-12-2018/gorillaa-movie-poster--5.jpg",
        category:"tamil",
    },
    {
        images:"https://www.indiaherald.com/Assets/ArticleUpload/202191111118925_1.jpg",
        category:"tamil",
    },
    {
        images:"https://1.bp.blogspot.com/-K1fBYzikYTA/XiBluvvig1I/AAAAAAAAAoM/uZnCwztBEGkkkc_rSE8X0qaEE99G7dLxQCLcBGAsYHQ/s1600/Bhoomi%2B%2B%25282%2529.jpg",
        category:"tamil",
    },
    {
        images:"  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSacMAYuTbZLydik7j8MNcdJwTq5KO-eiAlQ&usqp=CAU",
        category:"tamil",
    },
    {
        images:"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ecef6882970867.5d2dfc06d0bc0.jpg",
        category:"tamil",
    },
    {
        images:"https://mallurepost.com/upload/2021/01/16/Tamil-Movie-Eeswaran-Latest-movie-stills-88408.jpg",
        category:"tamil",
    },
    {
        images:"https://www.gethucinema.com/wp-content/uploads/2016/07/CmphIDsUsAA0V1p.jpg",
        category:"tamil",
    },
    {
        images:"https://images.cinemaexpress.com/uploads/user/ckeditor_images/article/2021/12/31/FH75JS0VUAMZ-5J.jpg?w=400&dpr=2.6",
        category:"tamil",
    },
    {
        images:"  https://igimages.gumlet.io/tamil/home/arya040422_1.jpg?w=376&dpr=2.6",
        category:"tamil",
    },
    {
        images:"https://www.indiewire.com/wp-content/uploads/2019/12/JokerPoster1200_5ca3c435318d42.29270548.jpg?w=800",
        category:"english",
    },
    {
        images:"https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/fefa3d53131197.5928e7ec97142.jpg",
        category:"english",
    },
    {
        images:"https://www.moviechant.com/media/images/2021/12/20/the-lost-city_movie_poster_3KIhz3P.jpg",
        category:"english",
    },
    {
        images:"https://wallpapercave.com/wp/wp10947960.jpg",
        category:"english",
    },
    {
        images:"https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/3ad58253131197.5928e7ec98295.jpg",
        category:"english",
    },
    {
        images:"https://www.themoviedb.org/t/p/original/g2V6uVSK6MVmI315h0rfWSaMoxP.jpg",
        category:"english",
    },
    {
        images:"https://webneel.net/file/images/11-16/1-star-trek-beyond-creative-movie-poster-design.jpg",
        category:"english",
    },
    {
        images:"https://i1.wp.com/teaser-trailer.com/wp-content/uploads/Johnny-English-3-1.jpg?ssl=1",
        category:"english",
    },
    {
        images:"https://www.boxofficemovies.in/now/wp-content/uploads/Maze-Runner-TheDeath-Cure-movie-poster.jpg",
        category:"english",
    },
    {
        images:"https://static.toiimg.com/photo/msid-89336487/89336487.jpg",
        category:"english",
    }, 
    {
        images:"https://i.pinimg.com/originals/df/00/f7/df00f7696ceaf06c59a7828496a1df30.jpg",
        category:"english",
    },
    {
        images:"https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F13%2F2017%2F10%2F06%2Fwanted1.jpg",
        category:"english",
    },
    {
        images:"https://image.tmdb.org/t/p/original/tOmYnPiCsmEWn8pmLQ523Nt5wGd.jpg",
        category:"english",
    },
    {
        images:"  https://1.bp.blogspot.com/-tdSc2ziLV0A/XjAXTV87hII/AAAAAAAAQI8/Vgv_3Rlyi5U4rxDHTQkTQjC62Wqhlz55gCLcBGAsYHQ/s1600/Bell-Bottom-movie-release-date-star-cast-poster.jpg",
        category:"hindi",
    },
    {
        images:"https://1.bp.blogspot.com/-IPquRofuKdc/XiVyjnvswjI/AAAAAAAAQFw/VW_h_ZQ9P5cvEMfe_dnJDzKCrE1Uyk1ewCLcBGAsYHQ/s1600/shubh-mangal-zyada-saavdhan-movie-star-cast-release-date-poster.jpg",
        category:"hindi",
    },
    {
        images:"https://m.media-amazon.com/images/M/MV5BNTlmNDMzOWQtYzg4Ny00OWQ0LWFhN2MtNmQ2MDczZGZhNTU5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
        category:"hindi",
    },
    {
        images:"https://images.wedmegood.com/wp-content/uploads/2016/12/d30de39171f5fef920ab7b3ee0e9137d.jpg",
        category:"hindi",
    },
    {
        images:"https://1.bp.blogspot.com/-xyH0Qs6yPmI/Xvs0bhdcQPI/AAAAAAAAZ_s/9kRuWAaGKLoXcwq-Dz-cgswdrMV3eHYOQCLcBGAsYHQ/s1600/Bhuj-Movie-Poster.jpg",
        category:"hindi",
    },
    {
        images:"https://rukminim1.flixcart.com/image/416/416/k186fm80/movie/z/y/y/2019-dvd-ultra-hindi-kabir-singh-hd-hindi-movie-bollywood-movie-original-imafkuejt4xaxdpz.jpeg?q=70",
        category:"hindi",
    },
    {
        images:"https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Bharat_film_poster.jpg/220px-Bharat_film_poster.jpg",
        category:"hindi",
    },
    {
        images:"  https://image.scoopwhoop.com/w360/s4.scoopwhoop.com/anj2/5dd3c34850758d6730e4f44f/e5a30ca6-5032-4c7a-ab9b-6b37056e6629.jpg.webp",
        category:"hindi",
    },
    {
        images:"https://cdn.shopify.com/s/files/1/0969/9128/products/Uri_-_Hows_The_Josh_-_Bollywood_Patriotic_Hindi_Movie_Poster_e3956ace-3559-4ad2-a923-b69e2bce44bb.jpg?v=1570245960",
        category:"hindi",
    },
    {
        images:"https://d3aew4oo17ml6.cloudfront.net/images/photos/thumbnailfull/photos-2015-5-18-3-13-55.jpg?v=1.1.0",
        category:"hindi",
    },
    {
        images:"https://m.media-amazon.com/images/M/MV5BZmEyZmQ3MDItNmU2ZS00OTE2LTk3ZjItZmMwZDYxNmM3NDJkXkEyXkFqcGdeQXVyOTg3MTI0NjA@._V1_FMjpg_UX1000_.jpg",
        category:"hindi",
    },
    {
        images:"https://m.media-amazon.com/images/M/MV5BNGI1MTI1YTQtY2QwYi00YzUzLTg3NWYtNzExZDlhOTZmZWU0XkEyXkFqcGdeQXVyMDkwNTkwNg@@._V1_.jpg",
        category:"hindi",
    },
    {
        images:"https://s3.ap-south-1.amazonaws.com/flashmorning.com/PgY4MRGOSmmJ2ikBBXLbKQQoVPbmJ5rDUcgpgi0w.jpg",
        category:"hindi",
    },
  
]